services:
  app:
    container_name: app
    image: contable-java:1.0.0
    build:
      context: '.'
      dockerfile: Dockerfile
    environment:
      - 'POSTGRES_USER=myuser'
      - 'POSTGRES_PASSWORD=secret'
      - 'PGHOST=192.168.100.57'
      - 'PGPORT=5432'
      - 'PGDATABASE=contable'
    ports:
      - 8080:8080
    depends_on:
      - mysql
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=clot'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306:3306'
